cache: pip
language: python
python:
    - 2.7
    - 3.6
os: linux
sudo: required
dist: trusty

# command to install dependencies
install:
  - ./.travis/install.sh
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script:
- ./.travis/run.sh