cache: pip
language: python
python:
  - 2.7
  - 3.6
os: linux
sudo: required
dist: trusty

install:
  - chmod +x .travis/install.sh
  - .travis/install.sh
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - chmod +x .travis/run.sh
  - .travis/run.sh

deploy:
  provider: pypi
  user: uilianries
  password:
    secure: yGrLzRVZTkV9Sax7fEgJjxFBnkocZGwE5wtHy4hzaByI7SeUO3nKvDGiYESw0OnV0ri7LIZ8CauvH9ltyAkLiLZH3saV0z5c5l2f34R5vy3PoEgk1FG6Wv/HBVnYHY3d1IfzjwK9LZintIMkFkt7WYWgOR+FtaFUip81pAW8EbNe36RHms44dL74oZbvHH5fUBXIxwOxP5L+6+H3tob4YQKlP59GgxeGhv8QfpHHMEHDiwbBDeooV1aD4o1VXc2Aw/6n1rnGRELUaxz+5XwnhW5Uw+bMS6sG7GwQb00R/AOCWa4tT+fo643Hh8xtWb1dfNh+0Qcy4gkzZ7Ebwinz+skEmiS7zMWBhnuNJaJicKvUMHgOoB3Q0sqsFaEXYVVGXVh5ZTFYfQKNdASXg8G/A0cLRyFB1JKGi3McBTMs7cjvLhA3E1XZifP1S/Lx3u4tJojS8ZWgDpy9g5DvD4cefO8UZkyzO2r0Prh10EA+Z7EFn+M/hHdwahd++OzEV/L0/SAOUze1ki/SKHYdICUd3P/lqzCKF4eOadEwuqA9Rgj5Yk9A8w1adImhxc20rfIOPUk5vqReXagxg1z4pDcHa7rsmkN/XceIed/pU16H4X9IkQoXFiLjo7svm5Bak5MZl9M7KefiOLusGVOOqmIb7GhVKR4DSQPqA/SDMwWIcJY=
