os: linux
dist: trusty

cache: pip
language: python
python:
  - 2.7
  - 3.6

addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - libsasl2-dev
      - python-dev
      - libldap2-dev
      - libssl-dev

install:
  - chmod +x .travis/install.sh
  - ".travis/install.sh"

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - chmod +x .travis/run.sh
  - ".travis/run.sh"

after_success:
  - codecov

deploy:
  provider: pypi
  user: uilianries
  password:
    secure: m53R1xVryG63qFQ/so9EhWFRLmnmxHIImsTR03mGonKrhFTl31pdP8YAbDAaEVx+SttKNeDZH9D5fS1RaDPA0h3RZbP8nZ6nz08kUV0chaF/bQc2j5Za3XtLEqd8ZUxudQlZdqQTfRnnyXIBP9AjRo2eTRhDl7qQvwWwLxAxic3Bl/yYFrgTm8I6bsi6BJ4vOaVGfiSrItXny9oEfiPpnG5+tBmhPm910QlZxaiBIe2mfkmxRFx3UaGruXPWQ5C6g2yt++ixixKEUfMED6A1t63vBdDGTAal+iKU3Oc10afr6yi7SpCRTgDOqEXqsofqVU/llha57yKKasitI24+8eoySFVoS/r3ziW3DZTivZ/Tay4bXTQYg2ZZCDLxYGxrR+CVvz8jQPaJlN98M7kc+36h378/3cJ9CUQ3658SCNWb6JjcrTnzXjwKYUv3mo7QB5ZlRoZNHuGriKGE1XU+FZkNPt/ixwZDEVwRAD1O1ag9nmHHo1okSX9G8FrQjKixSz8jY8lAAcFizIx8s7GUa1X+O9aBy5/lnMRXU4cgV8y0NdLjHnvezz8BYegYGM8KmnpVqiEyfyPCeZhq7dNY9C0v93BeosfPsZ5boY6vK9WEYDPQrUM3fK9wA1loPhaNWHvVrg6MEwxBKHvjA/FAJTgPDwNf689AhbfMbY7wYZY=
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = '2.7'"
