on: [push, pull_request, workflow_dispatch]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install APT packages
      run: sudo apt-get install -y gcc-multilib g++-multilib libsasl2-dev python-dev libldap2-dev
    - name: Install dependencies
      run: |
        chmod +x .github/workflows/install.sh
        .github/workflows/install.sh
    - name: ${{ matrix.config.name }}
      run: |
        chmod +x .github/workflows/run.sh
        .github/workflows/run.sh
    - name: Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)

  deploy_release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install pygithub
    - name: Generate Dist/
      run: python setup.py sdist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
